version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      PYTHONPATH: ${PYTHONPATH}
    volumes:
      - ./backend:/app
    ports:
      - 8081:8000
    command: bash
    tty: true
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ./db/my.cnf:/etc/my.cnf
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    # command: sh -c "cd vite-app && npm run dev"
    ports:
      - 4000:5173
    volumes:
      - ./front:/app
    stdin_open: true
    tty: true
volumes:
  db-store:
